# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favorite',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
